var gachaList = [
    'images/eggs/whaleegg.png',
    'images/eggs/goldenegg.png',
    'images/eggs/goldenegg.png',
    'images/eggs/angryegg.png',
    'images/eggs/angryegg.png',
    'images/eggs/angryegg.png',
    'images/eggs/worldegg.png',
    'images/eggs/worldegg.png',
    'images/eggs/disappointmentegg.png',
    'images/eggs/disappointmentegg.png',
    'images/eggs/joyegg.png',
    'images/eggs/joyegg.png',
    'images/eggs/exciteegg.png',
    'images/eggs/exciteegg.png',
    'images/eggs/yellowglitteregg.png',
    'images/eggs/yellowglitteregg.png',
    'images/eggs/yellowglitteregg.png',
    'images/eggs/greenglitteregg.png',
    'images/eggs/greenglitteregg.png',
    'images/eggs/greenglitteregg.png',
    'images/eggs/whiteegg.png',
    'images/eggs/whiteegg.png',
    'images/eggs/whiteegg.png',
    'images/eggs/pinkegg.png',
    'images/eggs/pinkegg.png',
    'images/eggs/pinkegg.png',
    'images/eggs/staregg.png',
    'images/eggs/staregg.png',
    'images/eggs/staregg.png',
    'images/eggs/checkeredegg.png',
    'images/eggs/checkeredegg.png',
    'images/eggs/checkeredegg.png',
    'images/eggs/cowboyegg.png',
    'images/eggs/cowboyegg.png',
    'images/eggs/cowboyegg.png',
    'images/eggs/cowboyegg.png',
    'images/eggs/chocolateegg.png',
    'images/eggs/chocolateegg.png',
    'images/eggs/chocolateegg.png',
    'images/eggs/greenegg.png',
    'images/eggs/greenegg.png',
    'images/eggs/greenegg.png',
    'images/eggs/greenegg.png',
    'images/eggs/greenegg.png',
    'images/eggs/crackedegg.png',
    'images/eggs/crackedegg.png',
    'images/eggs/crackedegg.png',
    'images/eggs/crackedegg.png',
    'images/eggs/crackedegg.png',
    'images/eggs/clayegg.png',
    'images/eggs/clayegg.png',
    'images/eggs/clayegg.png',
    'images/eggs/clayegg.png',
    'images/eggs/clayegg.png',
    'images/eggs/redegg.png',
    'images/eggs/redegg.png',
    'images/eggs/redegg.png',
    'images/eggs/redegg.png',
    'images/eggs/redegg.png',
    'images/eggs/blueegg.png',
    'images/eggs/blueegg.png',
    'images/eggs/blueegg.png',
    'images/eggs/blueegg.png',
    'images/eggs/blueegg.png',
    'images/eggs/purpleegg.png',
    'images/eggs/purpleegg.png',
    'images/eggs/purpleegg.png',
    'images/eggs/purpleegg.png',
    'images/eggs/purpleegg.png',
];

var gachaListDesc = [
    '[UR] Whale Egg: A majestic egg who is rich in sea.',
    '[UR] Golden Egg: The fabled golden egg, which is coveted by many.',
    '[UR] Golden Egg: The fabled golden egg, which is coveted by many.',
    '[SR] Angry Egg: An egg whose power is so vast, its anger is radiating out of its shell.',
    '[SR] Angry Egg: An egg whose power is so vast, its anger is radiating out of its shell.',
    '[SR] Angry Egg: An egg whose power is so vast, its anger is radiating out of its shell.',
    '[SR] World Egg: Rumors say this egg is linked to our planet.',
    '[SR] World Egg: Rumors say this egg is linked to our planet.',
    '[SR] Disappointment Egg: An egg which represents a feeling of disappointment.',
    '[SR] Disappointment Egg: An egg which represents a feeling of disappointment.',
    '[SR] Joy Egg: A happy egg.',
    '[SR] Joy Egg: A happy egg.',
    '[SR] Excitement Egg: An egg who is expecting great things to happen... soon.',
    '[SR] Excitement Egg: An egg who is expecting great things to happen... soon.',
    '[R] Yellow Glitter Egg: An egg who shines bright.',
    '[R] Yellow Glitter Egg: An egg who shines bright.',
    '[R] Yellow Glitter Egg: An egg who shines bright.',
    '[R] Green Glitter Egg: An egg who got a touch-me-up with the use of glitter.',
    '[R] Green Glitter Egg: An egg who got a touch-me-up with the use of glitter.',
    '[R] Green Glitter Egg: An egg who got a touch-me-up with the use of glitter.',
    '[R] White Egg: An ordinary white egg.',
    '[R] White Egg: An ordinary white egg.',
    '[R] White Egg: An ordinary white egg.',
    '[R] Pink Egg: An egg who loves unicorns.',
    '[R] Pink Egg: An egg who loves unicorns.',
    '[R] Pink Egg: An egg who loves unicorns.',
    '[R] Star Egg: Popular to children and astronomists.',
    '[R] Star Egg: Popular to children and astronomists.',
    '[R] Star Egg: Popular to children and astronomists.',
    '[R] Checkered Egg: This egg\'s got too many tattoos.',
    '[R] Checkered Egg: This egg\'s got too many tattoos.',
    '[R] Checkered Egg: This egg\'s got too many tattoos.',
    '[R] Cowboy Egg: An egg from the wild west...',
    '[R] Cowboy Egg: An egg from the wild west...',
    '[R] Cowboy Egg: An egg from the wild west...',
    '[R] Cowboy Egg: An egg from the wild west...',
    '[R] Chocolate Egg: A sweet treat who doesn\'t have yolk inside it.',
    '[R] Chocolate Egg: A sweet treat who doesn\'t have yolk inside it.',
    '[R] Chocolate Egg: A sweet treat who doesn\'t have yolk inside it.',
    '[C] Green Egg: A sickly egg who needs to lie down for a bit.',
    '[C] Green Egg: A sickly egg who needs to lie down for a bit.',
    '[C] Green Egg: A sickly egg who needs to lie down for a bit.',
    '[C] Green Egg: A sickly egg who needs to lie down for a bit.',
    '[C] Green Egg: A sickly egg who needs to lie down for a bit.',
    '[C] Cracked Egg: This egg has been dropped, but it still holds itself.',
    '[C] Cracked Egg: This egg has been dropped, but it still holds itself.',
    '[C] Cracked Egg: This egg has been dropped, but it still holds itself.',
    '[C] Cracked Egg: This egg has been dropped, but it still holds itself.',
    '[C] Cracked Egg: This egg has been dropped, but it still holds itself.',
    '[C] Clay Egg: Clay molded into an egg.',
    '[C] Clay Egg: Clay molded into an egg.',
    '[C] Clay Egg: Clay molded into an egg.',
    '[C] Clay Egg: Clay molded into an egg.',
    '[C] Clay Egg: Clay molded into an egg.',
    '[C] Red Egg: Its not evil; Red Egg is a red egg.',
    '[C] Red Egg: Its not evil; Red Egg is a red egg.',
    '[C] Red Egg: Its not evil; Red Egg is a red egg.',
    '[C] Red Egg: Its not evil; Red Egg is a red egg.',
    '[C] Red Egg: Its not evil; Red Egg is a red egg.',
    '[C] Blue Egg: An egg that fell from the sky.',
    '[C] Blue Egg: An egg that fell from the sky.',
    '[C] Blue Egg: An egg that fell from the sky.',
    '[C] Blue Egg: An egg that fell from the sky.',
    '[C] Blue Egg: An egg that fell from the sky.',
    '[C] Purple Egg: Very goth egg.',
    '[C] Purple Egg: Very goth egg.',
    '[C] Purple Egg: Very goth egg.',
    '[C] Purple Egg: Very goth egg.',
    '[C] Purple Egg: Very goth egg.',
];

var drawCount = 0;
drawCount = parseInt(localStorage.getItem('draw_counter'))+1;
localStorage.setItem("draw_counter", drawCount);

var drawOneCount = 0;
drawOneCount = parseInt(localStorage.getItem('draw_one_counter'))+1;
localStorage.setItem("draw_one_counter", drawOneCount);

localStorage.setItem("DrawResultListCount", 1);
localStorage.setItem("DrawResult1", pullOne());

function pullOne() {
    var img = '<img src=\"';
    var randomIndex = Math.floor(Math.random() * gachaList.length);
    img += gachaList[randomIndex];
    img += '\" alt=\"';
    img += gachaListDesc[randomIndex];
    img += '\" title=\"';
    img += gachaListDesc[randomIndex];
    img += '\" class=\"gachaResult\"/> \n';
    return img;
}